sudo: required

services:
  - docker

script:
- make cog-book
- touch build/cog-book/html/.nojekyll

notifications:
  slack:
    secure: IHbsXPBcld/MZ9qiTMkWx86lOlvDbblCmrqp+fbzSCEkwmvsGYiupJobPaA9+ACIAYUG45BpOVO5X7XB331OZbaIvBgoYuYt9+hSqNanVS8xwvvI0fqtLXQdtnBVxIfppuaHTDLOHF6TsQ5qVnExckh2g+ZJpSY76bd8RYpu18RS1etjBzlMWB+5/fgHzDMgEJ6qCcfm25PhTzSBSUHdkaKyuO25jn16tb9CrWL5VnPXpG+pyu0XqKvUaJ9YHD8K5ubQJWH+guMy4A5GTIID2BLKW22TiG64YZoaYKjLSMn2fOVqlV9C5i1P/XkVABQutXx9lSLavqokge6Na/x/l3QHfbz0eQfLFkAw9YGUOBV9rvLWFwHUIWLHTPb5igkLuvaVXGDDezpCY68SOSFHfECkAP36aNouVRf2Osrz7lcKCnkpVEJZ1Z6/UlahvhAya8z08wEdehqE9uqYzmsbUf3M7fhNHSvOWElU+QE3ymcuNnQeTBkEIped18jsmI4vvcynIHRKT8qH5NmZQkLN16xP/PvuFafzWw7e54HDY7Gu5jlSYRmcCP74fD2p2g8KZyTcHISv2HmzNQbn/OdX0cSLdyVR8N9ckRS0aWMeTJbc4bK+iDnTIF3FZcT0cf3KecJMm6ZPDnFrol5ReN8G3EXX8km17jjOhxYpe3wLu8E=

deploy:
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build/cog-book/html
  on:
    branch: master
