---
TWITTER_DEFAULT_ACCOUNT: STATUS # <1>

TWITTER_CONSUMER_KEY_STATUS: XXXX # <2>
TWITTER_CONSUMER_SECRET_STATUS: XXXX
TWITTER_ACCESS_TOKEN_STATUS: XXXX
TWITTER_ACCESS_TOKEN_SECRET_STATUS: XXXX

TWITTER_CONSUMER_KEY_MARKETING: YYYY # <3>
TWITTER_CONSUMER_SECRET_MARKETING: YYYY
TWITTER_ACCESS_TOKEN_MARKETING: YYYY
TWITTER_ACCESS_TOKEN_SECRET_MARKETING: YYYY
