---
cog_bundle_version: 4
name: twitter_example
description: Interact with Twitter
version: 0.0.5                      # <1>
docker: # <2>
  image: cog-book/twitter
  tag: latest
permissions:
  - twitter_example:tweet
commands:
  tweet:
    description: Send a tweet!
    executable: /home/bundle/tweet_cog_wrapper.sh # <3>
    arguments: "<message>"
    rules:
      - when command is twitter_example:tweet must have twitter_example:tweet
    options:
      as:
        description: the account to tweet from
        type: string
        required: false
        short_flag: a
templates:
  tweet:
    body: |
      ~each var=$results~
      ~$item.url~
      ~end~
