---
cog_bundle_version: 4

name: twitter_example
description: Interact with Twitter
version: 0.0.6
docker:
  image: cog-book/twitter
  tag: latest
permissions:
  - twitter_example:tweet
commands:
  tweet:
    description: Send a tweet!
    executable: /home/bundle/tweet_cog_wrapper.sh
    arguments: "<message>"
    rules:
      - when command is twitter_example:tweet must have twitter_example:tweet
    options:
      as:
        description: the account to tweet from
        type: string
        required: false
        short_flag: a
  recent_tweets: # <1>
    description: Last 5 tweets sent from this account
    executable: /home/bundle/recent_tweets.rb
    options:
      as:
        description: the account to tweet from
        type: string
        required: false
        short_flag: a
    rules:
      - allow
  stats: # <2>
    description: Favorites and retweets
    arguments: "[tweet_url]"
    executable: /home/bundle/stats.rb
    rules:
      - allow

templates:
  tweet:
    body: |
      ~each var=$results~
      ~$item.url~
      ~end~
  stats: # <3>
    body: |
      | Tweet | Favorite Count | Retweet Count |
      |-------|----------------|---------------|
      ~each var=$results~
      |~$item.message~|~$item.favorites~|~$item.retweets~|
      ~end~
