---
cog_bundle_version: 4

name: twitter_example
description: Interact with Twitter
version: 0.0.7 # <1>
docker: # <2>
  image: cog-book/twitter
  tag: latest
permissions:
  - twitter_example:tweet
commands:
  tweet:
    description: Send a tweet!
    executable: /home/bundle/tweet_cog_wrapper.sh # <3>
    arguments: "<message>"
    rules:
      - when command is twitter_example:tweet must have twitter_example:tweet
    options:
      as:
        description: the account to tweet from
        type: string
        required: false
        short_flag: a
  stats:
    description: Favorites and retweets
    executable: /home/bundle/stats_cog_wrapper.sh # <4>
    rules:
      - allow
  recent_tweets:
    description: Last 20 tweets sent from this account
    executable: /home/bundle/recent_cog_wrapper.sh # <5>
    rules:
      - allow
templates:
  tweet:
    body: |
      ~each var=$results~
      ~$item.url~
      ~end~
  stats:
    body: |
      | Tweet | Favorite Count | Retweet Count |
      |-------|----------------|---------------|
      ~each var=$results~
      |~$item.message~|~$item.favorites~|~$item.retweets~|
      ~end~
